package janitor

import (
	"github.com/kube-open-shape/kube-open-shape/internal/edge/graph"
	"github.com/kube-open-shape/kube-open-shape/internal/edge/knowledge"
)

// EvaluateSafety walks the authority handoff graph upward from a resource
// to determine its actionability. The walk uses a generic reconciliation model:
//
//	Continuous + Active  → Protected
//	Continuous + Unknown → Indeterminate
//	None                 → Actionable (safety qualification continues)
//	Unknown mode         → Indeterminate
//
// Authority relationships (Reconciles, Generates) never enter the teardown DAG.
// They produce Protected or Indeterminate, never ordering constraints.
func EvaluateSafety(resourceKey string, g *graph.Graph, index *knowledge.Index) SafetyResult {
	if g == nil {
		return SafetyResult{
			Actionability: ActionabilityIndeterminate,
			Reason:        "graph unavailable",
		}
	}

	// Walk 1: Check if the resource itself is directly reconciled
	result := checkReconciliation(resourceKey, g, index)
	if result != nil {
		return *result
	}

	// Walk 2: Check if the resource is a member of a group that is reconciled
	for _, edge := range g.IncomingEdges(resourceKey) {
		if edge.Type == graph.MemberOf {
			groupResult := checkReconciliation(edge.Source, g, index)
			if groupResult != nil {
				return *groupResult
			}
		}
	}

	// Walk 3: Check outgoing MemberOf edges (resource → group)
	for _, edge := range g.OutgoingEdges(resourceKey) {
		if edge.Type == graph.MemberOf {
			groupResult := checkReconciliation(edge.Target, g, index)
			if groupResult != nil {
				return *groupResult
			}
		}
	}

	// No authority found — resource is actionable
	return SafetyResult{
		Actionability: ActionabilityActionable,
		Reason:        "no active authority detected",
	}
}

// checkReconciliation examines whether a resource/group has an active reconciler
// and determines its actionability using the generic authority model.
func checkReconciliation(key string, g *graph.Graph, index *knowledge.Index) *SafetyResult {
	// Look for incoming Reconciles edges (Application → this resource/group)
	reconcilerKey := findReconciler(key, g)
	if reconcilerKey == "" {
		return nil
	}

	// Determine authority properties from the reconciler
	authority := resolveAuthority(reconcilerKey, g, index)

	// Apply the generic reconciliation model
	switch authority.ReconciliationMode {
	case ReconciliationContinuous:
		switch authority.State {
		case AuthorityStateActive:
			return &SafetyResult{
				Actionability: ActionabilityProtected,
				Reason:        "active continuous reconciliation (" + joinEvidence(authority.Evidence) + ")",
				Authority:     &authority,
			}
		case AuthorityStateInactive:
			return &SafetyResult{
				Actionability: ActionabilityIndeterminate,
				Reason:        "continuous reconciler present but inactive",
				Authority:     &authority,
			}
		default: // Unknown
			return &SafetyResult{
				Actionability: ActionabilityIndeterminate,
				Reason:        "continuous reconciler present, state unknown",
				Authority:     &authority,
			}
		}

	case ReconciliationNone:
		// Provenance authority (Helm, Terraform) — does not block action
		return nil

	default: // Unknown
		return &SafetyResult{
			Actionability: ActionabilityIndeterminate,
			Reason:        "authority present, reconciliation mode unknown",
			Authority:     &authority,
		}
	}
}

// resolveAuthority determines the reconciliation properties of a resource
// by inspecting its annotations and upstream generator chain.
func resolveAuthority(key string, g *graph.Graph, index *knowledge.Index) Authority {
	rec, ok := index.Get(key)
	if !ok {
		return Authority{
			ReconciliationMode: ReconciliationUnknown,
			State:              AuthorityStateUnknown,
			Key:                key,
		}
	}

	// Check for explicit auto-reconcile annotation (ArgoCD sync policy detection)
	autoReconcile := rec.Annotations["knowledge.kos.io/auto-reconcile"]
	if autoReconcile == "true" {
		return Authority{
			ReconciliationMode: ReconciliationContinuous,
			State:              AuthorityStateActive,
			Evidence:           []string{"auto-reconcile annotation on " + key},
			Key:                key,
		}
	}

	// Check if this reconciler is generated by an upstream ApplicationSet
	generatorKey := findGenerator(key, g)
	if generatorKey != "" {
		genAuthority := resolveGeneratorAuthority(generatorKey, index)
		if genAuthority.ReconciliationMode == ReconciliationContinuous {
			return Authority{
				ReconciliationMode: ReconciliationContinuous,
				State:              genAuthority.State,
				Evidence:           append([]string{"generated by " + generatorKey}, genAuthority.Evidence...),
				Key:                generatorKey,
			}
		}
		// Generator exists but doesn't have continuous reconciliation;
		// the Application is still generated and will be recreated if deleted
		return Authority{
			ReconciliationMode: ReconciliationContinuous,
			State:              AuthorityStateActive,
			Evidence:           []string{"generated by active ApplicationSet " + generatorKey},
			Key:                generatorKey,
		}
	}

	// Reconciler exists without auto-sync and without generator
	// This is a manual ArgoCD Application — still a reconciler but not continuous
	if autoReconcile == "false" {
		return Authority{
			ReconciliationMode: ReconciliationNone,
			State:              AuthorityStateActive,
			Evidence:           []string{"manual sync Application " + key},
			Key:                key,
		}
	}

	// No explicit annotation — cannot determine reconciliation mode
	return Authority{
		ReconciliationMode: ReconciliationUnknown,
		State:              AuthorityStateUnknown,
		Evidence:           []string{"reconciler present without reconciliation mode evidence"},
		Key:                key,
	}
}

// resolveGeneratorAuthority determines the authority properties of an ApplicationSet
// or other generator resource.
func resolveGeneratorAuthority(key string, index *knowledge.Index) Authority {
	rec, ok := index.Get(key)
	if !ok {
		return Authority{
			ReconciliationMode: ReconciliationUnknown,
			State:              AuthorityStateUnknown,
			Key:                key,
		}
	}

	autoReconcile := rec.Annotations["knowledge.kos.io/auto-reconcile"]
	if autoReconcile == "true" {
		return Authority{
			ReconciliationMode: ReconciliationContinuous,
			State:              AuthorityStateActive,
			Evidence:           []string{"auto-reconcile on generator " + key},
			Key:                key,
		}
	}

	// ApplicationSets by nature generate and maintain Applications — treat as continuous
	if rec.Identity.GVK.Kind == "ApplicationSet" {
		return Authority{
			ReconciliationMode: ReconciliationContinuous,
			State:              AuthorityStateActive,
			Evidence:           []string{"ApplicationSet generates and maintains Applications"},
			Key:                key,
		}
	}

	return Authority{
		ReconciliationMode: ReconciliationUnknown,
		State:              AuthorityStateUnknown,
		Key:                key,
	}
}

// findReconciler finds the Application that reconciles a resource (via Reconciles edge).
func findReconciler(resourceKey string, g *graph.Graph) string {
	for _, edge := range g.IncomingEdges(resourceKey) {
		if edge.Type == graph.Reconciles {
			return edge.Source
		}
	}
	return ""
}

// findGenerator finds the ApplicationSet that generates an Application (via Generates edge).
func findGenerator(applicationKey string, g *graph.Graph) string {
	for _, edge := range g.IncomingEdges(applicationKey) {
		if edge.Type == graph.Generates {
			return edge.Source
		}
	}
	return ""
}

// joinEvidence creates a human-readable summary of authority evidence.
func joinEvidence(evidence []string) string {
	if len(evidence) == 0 {
		return "no evidence"
	}
	if len(evidence) == 1 {
		return evidence[0]
	}
	result := evidence[0]
	for i := 1; i < len(evidence); i++ {
		result += "; " + evidence[i]
	}
	return result
}
